name: "✍️ Create a Task"
description: Create a new task.
labels: ["Type/Task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter product version.
    validations:
      required: false
  - type: input
    id: relatedIssue
    attributes:
      label: Related Issue
      description: Enter the parent issue related to this task.
    validations:
      required: false
