blank_issues_enabled: false
contact_links:
- name: Get help on OpenChoreo Slack Channel
  url: https://cloud-native.slack.com/archives/C0ABYRG1MND
  about: "Get help from the community on Slack."
- name: Engage with developer discussions in OpenChoreo Slack Channel
  url: https://cloud-native.slack.com/archives/C0ABHT902BY
  about: "Engage with the developers on Slack."
